### ISSUE TITLE
Convert big numbers to spreadsheet numbers, where possible

### ISSUE THREAD

**Issue by shoenseiwaso** [curvegrid/multibaas-for-google-sheets#36]
**Feature**
If the whole number part of a number returned from MultiBaas is less than `2^49`, the plugin should convert it to a number rather than leaving it as a string.

The implementation for this might be very simple: just ask MultiBaas to always return numbers as a number, rather than as a string. It's important to validate that this works for numbers converted as part of type conversions as well - some work on the MultiBaas side might be needed. This is probably preferable to attempting to parse numbers that come back via MultiBaas, especially in case they are being returned as arrays, multidimensional arrays, etc.

**Background**
Generally, what spreadsheet users care about is numbers for the sake of using numbers, not for the sake of reporting them. Google Sheets has an under-specified upper limit on the size of integer or floating point number which can be represented in a cell. The breakpoint for integers appears to be between `2^49` and `2^50`:

![image](https://user-images.githubusercontent.com/5861379/100620032-45279b80-3361-11eb-9ba4-696b008f0e64.png)

It is much more convenient to be dealing with numbers in spreadsheets rather than strings, which is how MultiBaas will return large numbers as strings by default, if the data type (pre-decimal shifting) is larger than 48 bits. With decimal shifting in MultiBaas type conversions, and the general size of numbers in practical use (1000 tokens, etc.), the practical size of numbers in general use tends to be well within the range of a spreadsheet. In many blockchain spreadsheet use cases, the whole number part (left of the decimal point) is much more important than the fractional part (right of the decimal point).

That is, losing some precision on the fractional part is probably an acceptable trade-off vs. having to convert all numbers from strings to numbers manually.

**Comment by daenamkim** [comment]
Also some related to

<img width="562" alt="Screen Shot 2020-12-02 at 14 01 17" src="https://user-images.githubusercontent.com/16159767/100830458-10256100-34a7-11eb-90d5-3830d38b7e6e.png">

**Comment by shoenseiwaso** [comment]
@daenamkim good call. For this issue/PR, let's not worry about Event Queries, since those don't yet go through type conversion/the "normal" MultiBaas flow.

**Comment by shoenseiwaso** [comment]
Resolved by #55, closing.
